//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSensor
    {
        public int SensorID { get; set; }
        public Nullable<System.DateTimeOffset> DateTimeOffset { get; set; }
        public string Name { get; set; }
        public string Element { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Status { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public Nullable<decimal> Maximum { get; set; }
        public string Fermenter { get; set; }
        public Nullable<bool> Actor { get; set; }
        public Nullable<bool> License { get; set; }
        public string Serial { get; set; }
    }
}
